### ISSUE TITLE
ReOrganize API + Backend File Organization

### ISSUE THREAD

**Issue by Cgunter1** [Hackerstat/website#48]
# Todos
- [x] Organize all interactions with the MongoDB database into their own functions and their own files.
- [x] Organize MongoDB function files into one MongoDB directory.
- [x] Organize all interactions with 3rd party APIs into their files and directory (i.e. utilities/thrdAPIs) like Medium RSS feeds and StackOverflow APIs.
- [x] Add Validating for params and body using yup.
