### ISSUE TITLE
Implement Jest Testing + Mocking System 

### ISSUE THREAD

**Issue by Cgunter1** [Hackerstat/website#49]
# Todos

- [ ]  Implement Testing System for API endpoints with Jest.

- [ ]  Implement Mocking System for MongoDB and 0Auth to be able to test API Endpoints.

- [ ] Create Unit-Tests for API Endpoints: NPM, StackOverflow, Github, and Medium.

**Comment by Cgunter1** [comment]
# Review
Unfortunately, unit-testing is going a bit on the back burner since there are more pressing features that need attention.
