### ISSUE TITLE
Dribbble integration - Frontend Implementation

### ISSUE THREAD

**Issue by Cgunter1** [Hackerstat/website#63]
# Todos

- [x] Implement user setting's page for [Dribbble](https://dribbble.com/) integration where the user can add their Dribbble username to HackerStat to retrieve that user's Dribbble portfolio pieces. This setting page should retrieve all portfolio pieces and have the user be able to select which portfolio pieces that they want to display (i.e. Max 6).
- [x] Implement Dribbble integration card that display's a HackerStat user's portfolio pieces:
    - [x] #80
    - [x] should be linked to the actual portfolio piece's webpage on Dribbble.

**Comment by Cgunter1** [comment]
# Todos

- [ ] Implement user setting's page for [Dribbble](https://dribbble.com/) integration where the user can add their Dribbble username to HackerStat to retrieve that user's Dribbble portfolio pieces. This setting page should retrieve all portfolio pieces and have the user be able to select which portfolio pieces that they want to display (i.e. Max 6).
- [ ] Implement Dribbble integration card that display's a HackerStat user's portfolio pieces:
    - [ ] when one of them is clicked should open an overlay window of the picture along with other associated pictures with that portfolio piece.
    - [ ] should be linked to the actual portfolio piece's webpage on Dribbble.
